
version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: messaging_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: messaging_pass
      MYSQL_HOST: db
      MYSQL_PORT: 3306

volumes:
  db_data: