name: contionus integration and delivery for docker image DRF messaging_app
on:
 push:
   branches:
     - main 
 pull_request:
  branches:
   - main
jobs:
  docker_actions:
    name: Docker
    runs_on: ubuntu-latest
    steps:
      -
       name: Set up QEMU
       uses: docker/setup-qemu-action@v3
      -
       name: login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{secrets.USERNAME}}
         password: ${{secrets.DOCKERHUB_TOKEN}}
      
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags:  messaging_app/portfolio:latest

