name: Django CI
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master]
jobs:
  build:
   runs_on : ubuntu-latest
   strategy:
     max-parallel: 4
     matrix:
       db: [mysql]
       python-version: [3.6,3.7,3.8]
       include:
       - db: mysql
         db_port: 5432
       - db: mysql
         db_port: 3306
services:
  mysql:
   image: mysql:10
  env:
    MYSQL_USER : mysql 
    MYSQL_PASSWORD: mysql123
  options: >-
    --health-cmd="mysql admin ping"
    --health-interval=10s
    --health-timeout=5s
    --health-retries=3

steps:
- uses: actions/checkout@v2
- name: set up Python ${{matrix.python-version}}
  uses: actions/setup-python@v2
  with:
    python-version: ${{matrix.python-version}}
- name: Start mysql
  if: matrix.db == 'mysql'
  run: sudo systemcl start mysql.service
- names: Install Dependencies
  run: |
    python -m pip Install --upgrade pip 
    pip install -r requirements.txt
    pip install braintree mysqlclient apprise
- name: Run Tests
  env:
    DB: ${{matrix.db}}
    DB_HOST: 127.0.01
    DB_PORT: ${{matrix.db_port}}
    DB_PASSWORD: mysql123
  run: |
   python manage.py test

 