 # creating deployment manifest
apiVersion: apps/apiV1
kind: deployment
metadata:
  name : messaging_app
spec:
 replicas: 3
 selector:
  matchLabels:
   app : messaging_app 
  template:
   metadata:
    labels:
      app: messaging_app
      version: blue
    spec:
    containers:
    - name: messaging_app
      image: messaging_app:1.0
      ports:
      - containerPort: 80


 # blue service 
 apiVersion: v1
 kind: Service
 metadata:
  name: messaging_app-green-service
 spec:
  selector:
   app: messaging_app
   version: green
  ports:
  -protocol: TCP
  port: 80
  targetPort: 80